version: "3.8"

services:
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - postgres
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "development"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
