name: Run Test Suite

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup config
        run: |
          cp .github/workflows/configs/config.yaml src/main/resources/config.yaml
          cp .github/workflows/configs/config.test.yaml src/test/resources/config.test.yaml
          cp .github/workflows/configs/flyway.conf flyway/conf/flyway.conf
          cp .github/workflows/configs/logback-test.xml src/main/resources/logback-test.xml
      - name: Start containers
        run: docker-compose up -d --build
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build and Run Tests
        run: ./gradlew build
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.token }}
      - name: API tests
        run: ./gradlew run & APIURL=http://localhost:8000/api ./spec/run-api-tests.sh
